### ISSUE TITLE
Fix CSS issue possibly relating em values

### ISSUE THREAD

**Issue by va6996** [azwreith/elementary-browser#3]
In the settings page, history tab, the Today and Yesterday don't have the same font size and the favicon size too is different.

**Comment by ghost** [comment]
When trying to find the bug in the application, I was unable to open any of the pages you list with the problem. The buttons didn't work.

**Comment by azwreith** [comment]
@prestonkyles The pages currently are unlinked to the main application. You have to view them as regular html files.

**Comment by ghost** [comment]
Ok. I opened up the `settings.html` page but still can't seem to find the issue anywhere. I checked the size of the favicons and text and their the same no matter how I resized my browser. Here are my [results](http://imgur.com/Luwke7e).

**Comment by azwreith** [comment]
@va6996 Care to comment?

**Comment by va6996** [comment]
If you change the height of the favicon to .9em, the icon sizes vary. Also the fix for this issue was already merged.

**Comment by va6996** [comment]
Looks like the guy who fixed it sent a PR seperately.
